sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t bmstech/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bmstech/react-test npm test -- --coverage

after_success:
  docker build -t bmstech/multi-client ./client
  docker build -t bmstech/multi-nginx ./nginx
  docker build -t bmstech/multi-server ./server
  docker build -t bmstech/multi-worker ./worker
  # Log in to the docker CLI.
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub.
  docker push bmstech/multi-client
  docker push bmstech/multi-nginx
  docker push bmstech/multi-server
  docker push bmstech/multi-worker
